version: "2"

networks:
  app-tier:
    driver: bridge

services:

  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: microservice-strategist
    environment:
      - APP_HOST=0.0.0.0
      - APP_DEBUG=False
      - APP_SERVER=none
      - APP_CONFIG_PATH=./config.py
    volumes:
      - ./strategist:/app/
    ports:
      - "8000:8000"
    depends_on:
      - rabbitmq
    networks:
      - app-tier
    tty: true

  rabbitmq:
    image: bitnami/rabbitmq:latest
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_USERNAME=user
      - RABBITMQ_PASSWORD=password
      - RABBITMQ_VHOST=vhost
    networks:
      - app-tier
